# Generated by Django 2.0.4 on 2018-10-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.IntegerField(choices=[(0, '未预约'), (1, '已预约')], default=0)),
                ('appoint_time', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('taxi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appoint_car.Driver')),
            ],
        ),
    ]
