# Generated by Django 2.0.4 on 2018-10-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_car', '0003_auto_20181005_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='appoint_time',
        ),
        migrations.AddField(
            model_name='user',
            name='appoint_time',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
