# Generated by Django 2.0.4 on 2018-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_car', '0004_auto_20181005_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
