# Generated by Django 2.0.4 on 2018-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appoint_car', '0005_auto_20181005_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wx_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
